baseURL = "https://gagnenet.com/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Elijah Gagne's site"
theme = "uBlogger"
publishDir = "docs"

[params]
  version = "1.3.X"
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  images = ["headshot.jpeg"]

[menu]
  [[menu.main]]
    identifier = "Blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/post/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false

# Header config
[params.header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "auto"

[params.header.title]
  # URL of the LOGO
  logo = ""
  # title name
  name = "Elijah Gagne's site"
  # you can add extra information before the name (HTML format is supported), such as icons
  pre = ""
  # you can add extra information after the name (HTML format is supported), such as icons
  post = ""
  # whether to use typeit animation for title name
  typeit = false



#baseurl = "https://gagnenet.com/"
#copyright = "All rights reserved"
#languagecode = "en-US"
#
#pluralizelisttitles = false
#theme = "novela"
#title = "Elijah Gagne"
#
#paginate = 6
#
#[social]
#twitter = "https://twitter.com/elijahwgagne"
#github = "https://github.com/elijahgagne"
#linkedin = "https://www.linkedin.com/in/elijah-gagne"
#
#
##[[menu.main]]  # here are the buttons on the menu
##name = "Home" # Button will display as "Home"
##weight = 100 # the weight decides the position of the button (higher or lower)
##identifier = "home"
##pre = "<br />"
##url = "/"
##
##[[menu.main]]
##name = "Contact"
##weight = 0
##identifier = "contact" # this button will refer to a markdown file named "contact" in the content ##folder
##pre = "<br />"
##url = "/contact"
##
##[[menu.main]]
##name = "Blog"
##identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
##pre = "<br />"
##url = "/post"
##weight = 40
##
##[params]
##author = "Elijah Gagne"
##authorlocation = "Hartford, VT"
##authorwebsite = "https://gagnenet.com/"
##authorbio = "IT software and Security Engineer, Open source enthusiast."
##cover = "images/"
##description = "Whatever the mind of man can conceive and believe, it can achieve."
##githubName = "elijahgagne"
##hideHUGOSupport = false
##logo = "images/e.png"
###twitterName = "elijahwgagne"
###googleAnalyticsUserID = "UA-79101-12"
###customFooterPartial = "netlify.html"
##
##[permalinks]
##post = "/:slug/"
##
##[sitemap]
##ChangeFreq = ""
##Filename = "sitemap.xml"
##Priority = "-1"